// 개봉순배열 생성
const movies_launch = [
  {
    search: "아이언맨1",
    name_kr: "아이언맨",
    name_en: "Ironman 1",
    launch_year: "2008.04.30.",
    url: "https://www.youtube.com/watch?v=Q9OT3kEClMw",
    img: "img/poster/수정본-300/아이언맨.jpg",
    phase: "1",
    timeline: "3",
    next_movie: ["아이언맨2"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "제임스 로드", char_name: "" },
      { man_name: "오베디아 스탠", char_name: "" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "해피", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "진실은....내가 '아이언맨'입니다.",
      "토니 스타크/아이언맨",
      "로버트 다우니 주니어",
    ],
  },
  {
    search: "인크레더블 헐크",
    name_kr: "인크레더블 헐크",
    name_en: "Incredible Hulk",
    launch_year: "2008.06.12.",
    url: "https://www.youtube.com/watch?v=J87E6fDlWBw",
    img: "img/poster/수정본-300/인크레더블 헐크.jpg",
    phase: "1",
    timeline: "4",
    next_movie: ["어벤져스"],
    character: [
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "로스 장군", char_name: "" },
      { man_name: "토니 스타크", char_name: "" },
      { man_name: "에밀 브론스키", char_name: "어보미네이션" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: ["Hulk...Smash!!!!!!!", "브루스 배너", "에드워드 노튼"],
  },
  {
    search: "아이언맨2",
    name_kr: "아이언맨2",
    name_en: "Ironman2",
    launch_year: "2010.04.29.",
    url: "https://www.youtube.com/watch?v=9tf_YrfHItM&t=4s",
    img: "img/poster/수정본-300/아이언맨2.jpg",
    phase: "1",
    timeline: "5",
    next_movie: ["토르 : 천둥의 신", "어벤져스", "아이언맨3"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "제임스 로드", char_name: "워머신" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "이안 반코", char_name: "위플래시" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "해피", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "토니, 내 인생 일대 최고의 발명품은 바로 너란다",
      "하워드 스타크",
      "존 슬래터리",
    ],
  },
  {
    search: "토르 : 천둥의 신",
    name_kr: "토르 : 천둥의 신",
    name_en: "Thor : God of Thunder",
    launch_year: "2011.04.28.",
    url: "https://www.youtube.com/watch?v=CnHmAKvZEd4",
    img: "img/poster/수정본-300/토르1.jpg",
    phase: "1",
    timeline: "6",
    next_movie: ["어벤져스", "토르 : 다크월드"],
    character: [
      { man_name: "토르", char_name: "토르" },
      { man_name: "제인 포스터", char_name: "" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "오딘", char_name: "오딘" },
      { man_name: "셀빅 박사", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "클린트 바튼", char_name: "호크아이" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["space"],
    sentence: [
      "난 단 한번도 왕좌를 원한적 없어. 난 인정받기를 원했을 뿐이야",
      "로키",
      "톰 히들스턴",
    ],
  },
  {
    search: "캡틴 아메리카1",
    name_kr: "캡틴 아메리카 : 퍼스트어벤져",
    name_en: "Captain America : The First Avenger",
    launch_year: "2011.07.28.",
    url: "https://www.youtube.com/watch?v=iQP2ZG6bxvo&t=1491s",
    img: "img/poster/수정본-300/캡틴아메리카1.jpg",
    phase: "1",
    timeline: "1",
    next_movie: ["토르 : 천둥의 신", "어벤져스", "캡틴 아메리카 : 윈터솔져"],
    character: [
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "요한 슈미트", char_name: "레드 스컬" },
      { man_name: "페기 카터", char_name: "" },
      { man_name: "버키 반즈", char_name: "" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
      { man_name: "졸라 박사", char_name: "" },
    ],
    stone: ["space"],
    sentence: [
      "종일 싸울 수도 있어.",
      "스티브 로저스/캡틴 아메리카",
      "크리스 에반스",
    ],
  },
  {
    search: "어벤져스1",
    name_kr: "어벤져스",
    name_en: "Avengers",
    launch_year: "2012.04.26.",
    url: "https://www.youtube.com/watch?v=xjq5NDum_W0",
    img: "img/poster/수정본-300/어벤져스1.jpg",
    phase: "1",
    timeline: "7",
    next_movie: ["아이언맨3", "토르 : 다크월드", "캡틴 아메리카 : 윈터솔져"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "토르", char_name: "토르" },
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "클린트 바튼", char_name: "호크 아이" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "셀빅 박사", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["space", "mind"],
    sentence: [
      "저 이제 퇴근할게요. 저로 인해 영웅들이 하나로 뭉치길...",
      "필 콜슨 요원",
      "클락 그레그",
    ],
  },
  {
    search: "아이언맨3",
    name_kr: "아이언맨3",
    name_en: "Ironman3",
    launch_year: "2013.04.25.",
    url: "https://www.youtube.com/watch?v=zrfxAYXoigs",
    img: "img/poster/수정본-300/아이언맨3.jpg",
    phase: "2",
    timeline: "9",
    next_movie: ["어벤져스 : 에이지 오브 울트론"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "제임스 로드", char_name: "워머신" },
      { man_name: "알드리치 킬리언", char_name: "" },
      { man_name: "해피", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      '다른 건 다 뺏어가도, 한가지 절대 빼앗아 갈 수 없는게 있죠. "I am IRON MAN"',
      "토니 스타크/아이언맨",
      "로버트 다우니 주니어",
    ],
  },
  {
    search: "토르 : 다크월드",
    name_kr: "토르 : 다크월드",
    name_en: "Thor : The Dark World",
    launch_year: "2013.10.30.",
    url: "https://www.youtube.com/watch?v=w6uO3IHQ5f4",
    img: "img/poster/수정본-300/토르2.jpg",
    phase: "2",
    timeline: "8",
    next_movie: [
      "가디언즈 오브 갤럭시",
      "어벤져스 : 에이지 오브 울트론",
      "토르 : 라그나로크",
    ],
    character: [
      { man_name: "토르", char_name: "토르" },
      { man_name: "제인 포스터", char_name: "" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "오딘", char_name: "오딘" },
      { man_name: "말레키스", char_name: "말레키스" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "셀빅 박사", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["reality"],
    sentence: [
      "위대한 왕이 되기보다 위대한 남자가 되겠습니다.",
      "토르",
      "크리스 헴스워스",
    ],
  },
  {
    search: "캡틴 아메리카2",
    name_kr: "캡틴 아메리카 : 윈터솔져",
    name_en: "Captain America : The Winter Soldier",
    launch_year: "2014.03.26.",
    url: "https://www.youtube.com/watch?v=p3LzFlAIbUk",
    img: "img/poster/수정본-300/캡틴아메리카2.jpg",
    phase: "2",
    timeline: "10",
    next_movie: ["어벤져스 : 에이지 오브 울트론", "캡틴 아메리카 : 시빌 워"],
    character: [
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "버키 반즈", char_name: "윈터 솔져" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
      { man_name: "페기 카터", char_name: "" },
      { man_name: "졸라 박사", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
      { man_name: "완다 막시모프", char_name: "스칼렛 위치" },
      { man_name: "피에트로 막시모프", char_name: "퀵 실버" },
      { man_name: "샤론 카터", char_name: "" },
    ],
    stone: ["mind"],
    sentence: [
      "자유의 가치는 비싸지...하지만 나는 기꺼이 지불하겠어.",
      "스티브 로저스/캡틴 아메리카",
      "크리스 에반스",
    ],
  },
  {
    search: "가디언즈 오브 갤럭시1",
    name_kr: "가디언즈 오브 갤럭시",
    name_en: "Guardians of the Galaxy",
    launch_year: "2014.07.31.",
    url: "https://www.youtube.com/watch?v=oKkHGFMJ148",
    img: "img/poster/수정본-300/가오갤1.jpg",
    phase: "2",
    timeline: "11",
    next_movie: ["가디언즈 오브 갤럭시 VOL.2"],
    character: [
      { man_name: "피터 제이슨", char_name: "스타로드" },
      { man_name: "가모라", char_name: "가모라" },
      { man_name: "아서더글라스", char_name: "드랙스" },
      { man_name: "그루트", char_name: "그루트" },
      { man_name: "로켓", char_name: "로켓" },
      { man_name: "로난", char_name: "로난" },
      { man_name: "욘두", char_name: "욘두" },
      { man_name: "네뷸라", char_name: "네뷸라" },
      { man_name: "콜렉터", char_name: "콜렉터" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["reality", "power"],
    sentence: ["We are Groot.", "그루트", "빈 디젤"],
  },
  {
    search: "어벤져스 : 에이지 오브 울트론",
    name_kr: "어벤져스 : 에이지 오브 울트론",
    name_en: "Avengers : Age of Ultron",
    launch_year: "2015.04.23.",
    url: "https://www.youtube.com/watch?v=cslYu_VgDpM",
    img: "img/poster/수정본-300/어벤져스2.jpg",
    phase: "2",
    timeline: "13",
    next_movie: ["캡틴 아메리카 : 시빌 워", "토르 : 라그나로크"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "토르", char_name: "토르" },
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "클린트 바튼", char_name: "호크 아이" },
      { man_name: "제임스 로드", char_name: "워머신" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "셀빅 박사", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
      { man_name: "울트론", char_name: "울트론" },
      { man_name: "완다 막시모프", char_name: "스칼렛 위치" },
      { man_name: "피에트로 막시모프", char_name: "퀵 실버" },
      { man_name: "셀빅 박사", char_name: "" },
      { man_name: "비젼", char_name: "비젼" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
    ],
    stone: ["mind"],
    sentence: [
      "이 문을 나서는 순간, 너도 어벤져스야.",
      "클린트 바튼 / 호크 아이",
      "제레미 레너",
    ],
  },
  {
    search: "앤트맨1",
    name_kr: "앤트맨",
    name_en: "Ant-man",
    launch_year: "2015.09.03.",
    url: "https://www.youtube.com/watch?v=FtT0s2eAwf0",
    img: "img/poster/수정본-300/앤트맨.jpg",
    phase: "2",
    timeline: "14",
    next_movie: ["캡틴 아메리카 : 시빌 워", "앤트맨과 와스프"],
    character: [
      { man_name: "스캇 랭", char_name: "앤트맨" },
      { man_name: "행크 핌 박사", char_name: "" },
      { man_name: "호프 반 다인", char_name: "" },
      { man_name: "대런 크로스", char_name: "옐로우 자켓" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
      { man_name: "페기 카터", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "No, I'm Ant-Man! I know, it wasn't my idea.",
      "스캇 랭/앤트맨",
      "폴 러드",
    ],
  },
  {
    search: "캡틴 아메리카3",
    name_kr: "캡틴 아메리카 : 시빌 워",
    name_en: "Captain America : Civil War",
    launch_year: "2016.04.27.",
    url: "https://www.youtube.com/watch?v=WihKgBdcKh8",
    img: "img/poster/수정본-300/캡틴아메리카3.jpg",
    phase: "3",
    timeline: "15",
    next_movie: [
      "어벤져스 : 인피니티 워",
      "블랙위도우",
      "스파이더맨 : 홈커밍",
      "앤트맨과 와스프",
      "블랙 팬서",
    ],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "클린트 바튼", char_name: "호크 아이" },
      { man_name: "스탠 리", char_name: "" },
      { man_name: "로스 장군", char_name: "" },
      { man_name: "완다 막시모프", char_name: "스칼렛 위치" },
      { man_name: "버키 반즈", char_name: "윈터 솔져" },
      { man_name: "제임스 로드", char_name: "워머신" },
      { man_name: "비젼", char_name: "비젼" },
      { man_name: "제모 남작", char_name: "제모 남작" },
      { man_name: "스캇 랭", char_name: "앤트맨" },
      { man_name: "티 찰라", char_name: "블랙 팬서" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
      { man_name: "샤론 카터", char_name: "" },
      { man_name: "피터 파커", char_name: "스파이더맨" },
    ],
    stone: ["mind"],
    sentence: [
      "어벤져스는 사실 나보단 너에게 더 잘어울려. 난 18살부터 늘 혼자였었어, 군대에서도 어디에서도 잘 어울리지 못했지. 하지만 네가 날 필요로 하면 언제든 어디든 달려갈게 토니.",
      "스티브 로저스/캡틴 아메리카",
      "크리스 에반스",
    ],
  },
  {
    search: "닥터 스트레인지",
    name_kr: "닥터 스트레인지",
    name_en: "Doctor Strange",
    launch_year: "2016.10.26.",
    url: "https://www.youtube.com/watch?v=2ojyCukJOjw",
    img: "img/poster/수정본-300/닥터스트레인지.jpg",
    phase: "3",
    timeline: "18",
    next_movie: ["토르 : 라그나로크", "어벤져스 : 인피니티 워"],
    character: [
      { man_name: "스티븐 스트레인지", char_name: "닥터 스트레인지" },
      { man_name: "에인션트 원", char_name: "에인션트 원" },
      { man_name: "케실리우스", char_name: "케실리우스" },
      { man_name: "모르도 남작", char_name: "모르도 남작" },
      { man_name: "스탠 리", char_name: "" },
      { man_name: "도르마무", char_name: "도르마무" },
    ],
    stone: ["time"],
    sentence: [
      "이 광활한 멀티버스에서 넌 누구일까...?",
      "에인션트 원",
      "틸다 스윈튼",
    ],
  },
  {
    search: "가디언즈 오브 갤럭시 VOL.2",
    name_kr: "가디언즈 오브 갤럭시 VOL.2",
    name_en: "Guardians of the Galaxy Vol. 2",
    launch_year: "2017.05.03.",
    url: "https://www.youtube.com/watch?v=oKkHGFMJ148",
    img: "img/poster/수정본-300/가오갤2.jpg",
    phase: "3",
    timeline: "12",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "피터 제이슨", char_name: "스타로드" },
      { man_name: "가모라", char_name: "가모라" },
      { man_name: "아서더글라스", char_name: "드랙스" },
      { man_name: "그루트", char_name: "그루트" },
      { man_name: "로켓", char_name: "로켓" },
      { man_name: "맨티스", char_name: "맨티스" },
      { man_name: "에고", char_name: "에고" },
      { man_name: "욘두", char_name: "욘두" },
      { man_name: "네뷸라", char_name: "네뷸라" },
      { man_name: "콜렉터", char_name: "콜렉터" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "씨를 뿌렸다고 해서 아버지가 되는 것은 아니지.. 잘 못 키워서 미안하구나",
      "욘두",
      "마이클 루커",
    ],
  },
  {
    search: "스파이더맨 : 홈커밍",
    name_kr: "스파이더맨 : 홈커밍",
    name_en: "Spider-Man : Homecoming",
    launch_year: "2017.07.05.",
    url: "https://www.youtube.com/watch?v=mO168Yp2IF0",
    img: "img/poster/수정본-300/스파이더맨_홈커밍.jpg",
    phase: "3",
    timeline: "19",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "피터 파커", char_name: "스파이더맨" },
      { man_name: "아드리안 툼즈", char_name: "벌쳐" },
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "해피", char_name: "" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "미쉘 존스", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "수트 없이 아무것도 못한다면, 넌 더더욱 그 수트를 가질 자격이 없어.",
      "토니 스타크/아이언맨",
      "로버트 다우니 주니어",
    ],
  },
  {
    search: "토르 : 라그나로크",
    name_kr: "토르 : 라그나로크",
    name_en: "Thor : Ragnarok",
    launch_year: "2017.10.25.",
    url: "https://www.youtube.com/watch?v=18Ns_yUlkb4",
    img: "img/poster/수정본-300/토르3.png",
    phase: "3",
    timeline: "20",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "토르", char_name: "토르" },
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "오딘", char_name: "오딘" },
      { man_name: "헬라", char_name: "헬라" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "발키리", char_name: "발키리" },
      { man_name: "스티븐 스트레인지", char_name: "닥터 스트레인지" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "아스가르드는 장소가 아니야. 사람들이지.",
      "오딘",
      "안소니 홉킨스",
    ],
  },
  {
    search: "블랙 팬서1",
    name_kr: "블랙 팬서",
    name_en: "Black Panther",
    launch_year: "2018.02.14.",
    url: "https://www.youtube.com/watch?v=Kxi3AE7Nf5A",
    img: "img/poster/수정본-300/블랙팬서.jpg",
    phase: "3",
    timeline: "17",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "티 찰라", char_name: "블랙 팬서" },
      { man_name: "에릭 몽거", char_name: "" },
      { man_name: "슈리", char_name: "" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: [
      "현명한 자는 다리를 만들고 어리석은 자는 벽을 세운다.",
      "티 찰라 / 블랙 팬서",
      "채드윅 보스만",
    ],
  },
  {
    search: "어벤져스 : 인피니티 워",
    name_kr: "어벤져스 : 인피니티 워",
    name_en: "Avengers : Infinity War",
    launch_year: "2018.04.25.",
    url: "https://www.youtube.com/watch?v=ksZR8xjGuBA",
    img: "img/poster/수정본-300/어벤져스3.jpg",
    phase: "3",
    timeline: "22",
    next_movie: ["어벤져스 : 엔드게임"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "토르", char_name: "토르" },
      { man_name: "타노스", char_name: "타노스" },
      { man_name: "스티븐 스트레인지", char_name: "닥터 스트레인지" },
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "클린트 바튼", char_name: "호크 아이" },
      { man_name: "피터 파커", char_name: "스파이더맨" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "티 찰라", char_name: "블랙 팬서" },
      { man_name: "버키 반즈", char_name: "윈터 솔져" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "슈리", char_name: "" },
      { man_name: "완다 막시모프", char_name: "스칼렛 위치" },
      { man_name: "비젼", char_name: "비젼" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
      { man_name: "제임스 로드", char_name: "워머신" },

      { man_name: "피터 제이슨", char_name: "스타로드" },
      { man_name: "가모라", char_name: "가모라" },
      { man_name: "아서더글라스", char_name: "드랙스" },
      { man_name: "그루트", char_name: "그루트" },
      { man_name: "로켓", char_name: "로켓" },
      { man_name: "맨티스", char_name: "맨티스" },
      { man_name: "네뷸라", char_name: "네뷸라" },
      { man_name: "콜렉터", char_name: "콜렉터" },
      { man_name: "에이트리", char_name: "에이트리" },

      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["space", "mind", "power", "time", "soul", "reality"],
    sentence: [
      "실수한거야. 내 머리를 잘랐어야지.(핑거스냅)",
      "타노스",
      "조슈 브롤린",
    ],
  },
  {
    search: "앤트맨과 와스프",
    name_kr: "앤트맨과 와스프",
    name_en: "Ant-Man and the Wasp",
    launch_year: "2018.07.04.",
    url: "https://www.youtube.com/watch?v=DuwQio1nXwY",
    img: "img/poster/수정본-300/앤트맨과 와스프.jpg",
    phase: "3",
    timeline: "21",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "스캇 랭", char_name: "앤트맨" },
      { man_name: "호프 반 다인", char_name: "와스프" },
      { man_name: "행크 핌 박사", char_name: "" },
      { man_name: "재닛 반 다인", char_name: "" },
      { man_name: "에이바", char_name: "고스트" },
      { man_name: "스탠 리", char_name: "" },
    ],
    stone: [],
    sentence: ["Antman and Warsp will return?", "쿠키영상", "엔드게임 예고"],
  },
  {
    search: "캡틴 마블",
    name_kr: "캡틴 마블",
    name_en: "Captain Marvel",
    launch_year: "2019.03.06.",
    url: "https://www.youtube.com/watch?v=VXZmea13-V0",
    img: "img/poster/수정본-300/캡틴마블.jpg",
    phase: "3",
    timeline: "2",
    next_movie: ["어벤져스 : 엔드게임"],
    character: [
      { man_name: "캐럴 댄버스", char_name: "캡틴 마블" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "필 콜슨 요원", char_name: "" },
      { man_name: "로난", char_name: "로난" },
    ],
    stone: ["space"],
    sentence: [
      "너에게 증명할 것은 없어",
      "캐럴 댄버스 / 캡틴 마블",
      "브리 라슨",
    ],
  },
  {
    search: "어벤져스 : 엔드게임",
    name_kr: "어벤져스 : 엔드게임",
    name_en: "Avengers : Endgame",
    launch_year: "2019.04.24.",
    url: "https://www.youtube.com/watch?v=dNB_QMbwFWE",
    img: "img/poster/수정본-300/어벤져스4.jpg",
    phase: "3",
    timeline: "23",
    next_movie: ["스파이더맨 : 파 프롬 홈"],
    character: [
      { man_name: "토니 스타크", char_name: "아이언맨" },
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "토르", char_name: "토르" },
      { man_name: "타노스", char_name: "타노스" },
      { man_name: "스티븐 스트레인지", char_name: "닥터 스트레인지" },
      { man_name: "스티브 로저스", char_name: "캡틴 아메리카" },
      { man_name: "브루스 배너", char_name: "헐크" },
      { man_name: "클린트 바튼", char_name: "호크 아이" },
      { man_name: "피터 파커", char_name: "스파이더맨" },
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "티 찰라", char_name: "블랙 팬서" },
      { man_name: "로키", char_name: "로키" },
      { man_name: "페퍼 포츠", char_name: "" },
      { man_name: "슈리", char_name: "" },
      { man_name: "완다 막시모프", char_name: "스칼렛 위치" },
      { man_name: "비젼", char_name: "비젼" },
      { man_name: "헤임달", char_name: "헤임달" },
      { man_name: "샘 윌슨", char_name: "팔콘" },
      { man_name: "제임스 로드", char_name: "워머신" },
      { man_name: "버키 반즈", char_name: "윈터 솔져" },

      { man_name: "피터 제이슨", char_name: "스타로드" },
      { man_name: "가모라", char_name: "가모라" },
      { man_name: "아서더글라스", char_name: "드랙스" },
      { man_name: "그루트", char_name: "그루트" },
      { man_name: "로켓", char_name: "로켓" },
      { man_name: "맨티스", char_name: "맨티스" },
      { man_name: "네뷸라", char_name: "네뷸라" },
      { man_name: "콜렉터", char_name: "콜렉터" },
      { man_name: "에이트리", char_name: "에이트리" },

      { man_name: "캐럴 댄버스", char_name: "캡틴 마블" },
      { man_name: "발키리", char_name: "발키리" },
      { man_name: "호프 반 다인", char_name: "와스프" },
      { man_name: "에인션트 원", char_name: "에인션트 원" },
      { man_name: "페기카터", char_name: "" },
      { man_name: "행크 핌 박사", char_name: "" },
      { man_name: "해피", char_name: "" },
      { man_name: "제인 포스터", char_name: "" },

      { man_name: "스탠 리", char_name: "" },
    ],
    stone: ["space", "mind", "power", "time", "soul", "reality"],
    sentence: [
      "I AM IRON MAN.",
      "토니 스타크 / 아이언맨",
      "로버트 다우니 주니어",
    ],
  },
  {
    search: "스파이더맨 : 파 프롬 홈",
    name_kr: "스파이더맨 : 파 프롬 홈",
    name_en: "Spider-Man : Far From Home",
    launch_year: "2019.07.02.",
    url: "https://www.youtube.com/watch?v=zsehQ83TtjI",
    img: "img/poster/수정본-300/스파이더맨_파프롬홈.jpg",
    phase: "3",
    timeline: "24",
    next_movie: [],
    character: [
      { man_name: "닉 퓨리", char_name: "" },
      { man_name: "피터 파커", char_name: "스파이더맨" },
      { man_name: "해피", char_name: "" },
      { man_name: "미쉘 존스", char_name: "" },
      { man_name: "퀜틴 벡", char_name: "미스테리오" },
      { man_name: "J. 조너 제임슨", char_name: "편집장" },
    ],
    stone: [],
    sentence: [
      "왕관을 쓴 머리는 편안히 쉴 수 없다.",
      "닉 퓨리",
      "사무엘 L. 잭슨",
    ],
  },
  {
    search: "블랙위도우",
    name_kr: "블랙위도우",
    name_en: "Black Widow",
    launch_year: "2021.07.07.",
    url: "",
    img: "img/poster/수정본-300/블랙위도우.jpg",
    phase: "4",
    timeline: "16",
    next_movie: ["어벤져스 : 인피니티 워"],
    character: [
      { man_name: "나타샤 로마노프", char_name: "블랙 위도우" },
      { man_name: "옐레나 벨로바", char_name: "" },
      { man_name: "멜리나 보스토코프", char_name: "" },
      { man_name: "알렉세이 쇼스타코프", char_name: "레드 가디언" },
    ],
    stone: [],
    sentence: [
      "내겐 가족이 없는 줄 알았는데 둘이나 있더라고요. 한 가족은 감옥에 있으니 그들을 구하러 가야 해요.",
      "나타샤 로마노프/블랙 위도우",
      "스칼렛 요한슨",
    ],
  },

  {
    search: "샹치와 텐 링즈의 전설",
    name_kr: "샹치와 텐 링즈의 전설",
    name_en: "Shang-Chi and the Legend of the Ten Rings",
    launch_year: "2021. 09. 01.",
    url: "https://www.youtube.com/watch?v=Pj7CadRf82k",
    img: "img/poster/수정본-300/샹치.jpg",
    phase: "4",
    timeline: "25",
    next_movie: [],
    character: [{ man_name: "샹치", char_name: "샹치" }],
    stone: [],
    sentence: "",
  },
];

// 시간순배열 생성
const movies_time = [];

for (let t = 0; t < movies_launch.length; t++) {
  for (let l = 0; l < movies_launch.length; l++) {
    if (String(t + 1) === movies_launch[l].timeline) {
      movies_time.push(movies_launch[l]);
    }
  }
}

// 개봉예정배열 생성
const movies_schedule = [
  {
    search: "베놈 2 : 렛 데어 비 카니지",
    name_kr: "베놈 2 : 렛 데어 비 카니지",
    name_en: "Venom : Let There Be Carnage",
    launch_year: "2021. 10. 13.\n마블은 아니지만 추후 MCU 편입 가능성있음",
    url: "https://www.youtube.com/watch?v=BryJA-Xp-Q4",
    img: "img/poster/수정본-300/베놈2.jpg",
    phase: "",
    timeline: "",
    next_movie: [],
    character: [{ man_name: "에디 브록", char_name: "베놈" }],
    stone: [],
    sentence: "",
  },
  {
    search: "이터널스",
    name_kr: "이터널스",
    name_en: "Eternals",
    launch_year: "2021. 11. 5.",
    url: "https://www.youtube.com/watch?v=BdkSkI61aGo",
    img: "img/poster/수정본-300/이터널스.jpg",
    phase: "4",
    timeline: "26",
    next_movie: [],
    character: [{ man_name: "길가메쉬", char_name: "길가메쉬" }],
    stone: [],
    sentence: "",
  },
  {
    search: "스파이더맨 : 노 웨이 홈",
    name_kr: "스파이더맨 : 노 웨이 홈",
    name_en: "Spider-Man : No Way Home",
    launch_year: "2021. 12. 17",
    url: "https://www.youtube.com/watch?v=WgU7P6o-GkM&t=12s",
    img: "img/poster/수정본-300/스파이더맨_노웨이홈.jpg",
    phase: "4",
    timeline: "27",
    next_movie: [],
    character: [{ man_name: "피터 파커", char_name: "스파이더맨" }],
    stone: [],
    sentence: "",
  },
  {
    search: "닥터 스트레인지 인 더 멀티버스 오브 매드니스",
    name_kr: "닥터 스트레인지 인 더 멀티버스 오브 매드니스",
    name_en: "Doctor Strange in the Multiverse of Madness",
    launch_year: "2022. 3. 25.",
    url: "",
    img: "img/poster/수정본-300/닥터스트레인지2.jpg",
    phase: "4",
    timeline: "28",
    next_movie: [],
    character: [
      { man_name: "스티븐 스트레인지", char_name: "닥터 스트레인지" },
    ],
    stone: [],
    sentence: "",
  },
  {
    search: "토르 : 러브 앤 썬더",
    name_kr: "토르 : 러브 앤 썬더",
    name_en: "Thor : Love and Thunder",
    launch_year: "2022. 5. 6.",
    url: "",
    img: "img/poster/수정본-300/토르4.jpg",
    phase: "4",
    timeline: "29",
    next_movie: [],
    character: [{ man_name: "토르", char_name: "토르" }],
    stone: [],
    sentence: "",
  },
  {
    search: "블랙팬서: 와칸다 포에버",
    name_kr: "블랙팬서: 와칸다 포에버",
    name_en: "Black Panther: Wakanda Forever",
    launch_year: "2022. 7. 8.",
    url: "",
    img: "img/poster/수정본-300/블랙팬서2.jpg",
    phase: "4",
    timeline: "30",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
  {
    search: "더 마블스",
    name_kr: "더 마블스",
    name_en: "The Marvels",
    launch_year: "2022. 11. 11.",
    url: "",
    img: "img/poster/수정본-300/캡틴마블2.jpg",
    phase: "4",
    timeline: "31",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
  {
    search: "앤트맨과 와스프 : 퀀터매니아",
    name_kr: "앤트맨과 와스프 : 퀀터매니아",
    name_en: "Ant-man and the Wasp : Quantumania",
    launch_year: "2023. 2. 17.",
    url: "",
    img: "img/poster/수정본-300/앤트맨3.jpg",
    phase: "4",
    timeline: "32",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
  {
    search: "가디언즈 오브 갤럭시 VOL.3",
    name_kr: "가디언즈 오브 갤럭시 VOL.3",
    name_en: "Guardians of the Galaxy Vol. 3",
    launch_year: "2023. 5. 5.",
    url: "",
    img: "img/poster/수정본-300/가오갤3.jpg",
    phase: "4",
    timeline: "33",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
  {
    search: "마블 블레이드1",
    name_kr: "블레이드",
    name_en: "Blade",
    launch_year: "2023?",
    url: "",
    img: "img/poster/수정본-300/블레이드.jpg",
    phase: "4",
    timeline: "34",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
  {
    search: "마블 판타스틱4",
    name_kr: "판타스틱4",
    name_en: "Fantasitc4",
    launch_year: "2023?",
    url: "",
    img: "img/poster/수정본-300/판타스틱4.jpg",
    phase: "4",
    timeline: "35",
    next_movie: [],
    character: [{ man_name: "", char_name: "" }],
    stone: [],
    sentence: "",
  },
];

// 영화별 세부정보
const content_movies_info = [
  {
    search: "아이언맨1",
    synopsys:
      "천재적인 두뇌와 재능으로 세계 최강의 무기업체를 이끄는 CEO이자 타고난 매력으로 셀러브리티 못지않은 화려한 삶을 살아가던 억만장자 토니 스타크. 아프가니스탄에서 자신이 개발한 신무기 발표를 성공리에 마치고 돌아가던 그는 게릴라군의 갑작스런 공격에 의해 가슴에 치명적인 부상을 입고 게릴라군에게 납치된다. 가까스로 목숨을 건진 그에게 게릴라군은 자신들을 위한 강력한 무기를 개발하라며 그를 위협한다. 그러나 그는 게릴라군을 위한 무기 대신 탈출을 위한 무기가 장착된 철갑수트를 몰래 만드는 데 성공하고 그의 첫 수트인 ‘Mark1’를 입고 탈출에 성공한다. 미국으로 돌아온 토니 스타크는 자신이 만든 무기가 많은 사람들의 생명을 위협하고 세상을 엄청난 위험에 몰아넣고 있다는 사실을 깨닫고 무기사업에서 손 뗄 것을 선언한다. 그리고 Mark1을 토대로 최강의 하이테크 수트를 개발하는 데 자신의 천재적인 재능과 노력을 쏟아 붓기 시작한다. 탈출하는 당시 부서져버린 Mark1를 바탕으로 보다 업그레이드 된 수트 Mark2를 만들어낸 토니 스타크. 거기에 만족하지 않고 숱한 시행착오와 실패 끝에 자신의 모든 능력과 현실에서 가능한 최강의 최첨단 과학 기술이 집적된 하이테크 수트 Mark3를 마침내 완성 최강의 슈퍼히어로 ‘아이언맨’으로 거듭난다. 토니 스타크가 탈출하는 과정을 통해 Mark1의 가공할 위력을 확인한 게릴라 군은 토니 스타크가 미처 회수하지 못한 Mark1의 잔해와 설계도를 찾아낸다. Mark1을 재조립하여 그들의 목적을 이루기 위한 거대하고 강력한 철갑수트를 제작하려는 음모를 꾸미는 게릴라군. 토니 스타크가 갖고 있던 에너지원을 훔쳐 ‘아이언맨’을 능가하는 거대하고 강력한 ‘아이언 몽거’를 완성한 그들은 세계 평화를 위협하고 토니 스타크는 그들의 음모과 배후세력이 누구인지를 알게 되는데...!",
    starPoint: "8.92",
    audienceCount: "430만명",
    summary: "SF | 미국 | 125분",
  },
  {
    search: "인크레더블 헐크",
    synopsys:
      "실험 중 감마선에 노출된 이후 분노를 통제할 수 없는 상태가 되면 녹색 괴물 ‘헐크’로 변하게 되는 브루스 배너(에드워드 노튼). 필사적으로 치료제 개발에 매달리지만 그의 능력을 이용하려는 정부 군대의 끈질긴 추격을 받고 쫓기게 된다. 한편 헐크의 거대한 힘의 비밀을 파헤치던 이들은 헐크보다 더 파괴적인 ‘어보미네이션’을 만드는데 성공 도시 전체를 집어삼키려 한다. 이에 브루스 배너는 정상적인 인생을 되찾으려던 계획을 버리고 어보미네이션과 정부 군대 그리고 자기 자신과의 마지막 대결을 준비하는데...",
    starPoint: "8.28",
    audienceCount: "99만명",
    summary: "액션 | 미국 | 113분",
  },
  {
    search: "아이언맨2",
    synopsys:
      "세계 최강의 무기업체를 이끄는 CEO이자 타고난 매력으로 셀러브리티 못지않은 화려한 삶을 살아가던 토니 스타크. 기자회견을 통해 자신이 아이언맨이라고 정체를 밝힌 이후 정부로부터 아이언맨 수트를 국가에 귀속시키라는 압박을 받지만 이를 거부한 채 더욱 화려하고 주목 받는 나날을 보낸다. 스타크 인더스트리의 운영권까지 수석 비서였던 ‘페퍼포츠’에게 일임하고 슈퍼히어로로서의 인기를 만끽하며 지내던 토니 스타크. 하지만 그 시각 아이언맨의 수트 기술을 ‘스타크’ 가문에 빼앗긴 후 쓸쓸히 돌아가신 아버지의 복수를 다짐해 온 ‘위플래시’는 수트의 원천 기술 개발에 성공 치명적인 무기를 들고 직접 토니 스타크를 찾아 나선다. F-1 모나코 그랑프리에서 직접 경주용 차에 올라선 토니 스타크 앞에 나타난 위플래시! 무차별적으로 전기 채찍을 휘두르는 그의 공격에 무방비 상태였던 토니 스타크는 생명의 위협을 느끼지만 새롭게 개발한 휴대용 수트 Mark5를 이용하여 간신히 위험에서 벗어난다. 그리고 자신과 자신의 아버지에 대해 강한 적대감을 드러내는 그에게서 심상치 않은 위기를 직감한다. 한편 이 과정을 모두 지켜본 토니 스타크의 라이벌이자 무기업자인 ‘저스틴 해머’는 아이언맨에 필적할 만한 위플래시의 위력을 간파하고 그를 몰래 감옥에서 탈출시켜 자신과 손 잡을 것을 제안한다. 위플래시를 만난 이후 좀처럼 충격에서 헤어나오지 못하던 토니 스타크는 감옥에 갇혀 있는 줄 알았던 위플래시가 저스틴 해머와 함께 있음을 알게 되고 역대 수트들을 뛰어넘는 최강의 위력을 지닌 Mark6 개발에 박차를 가한다. 그 사이 저스틴 해머는 새로운 군무기 발표 쇼케이스를 개최하고 그 곳에서 위플래시는 모두를 놀라게 할 작전 실행에 나서는데...! 줄거리 2. 자신이 아이언맨이라고 정체를 밝힌 뒤 할리우드 스타 못지 않은 인기를 누리던 토니 스타크. 스타크 인더스트리의 운영권을 수석 비서였던 페퍼포츠에게 일임하고 즐거운 나날을 보내던 그에게 생애 최고의 위기가 찾아온다. ‘스타크’ 가문에 대한 적대감으로 가득 찬 ‘위플래시’가 아이언맨 수트의 원천 기술인 아크 원자로 개발에 성공한 것. F-1 그랑프리에 출전하여 무방비 상태에 있던 토니 스타크에게 위협적인 공격을 가하는 위플래쉬. 이에 토니 스타크는 새로 개발한 업그레이드 수트를 이용 겨우 위기를 모면한다. 하지만 이 사건을 계기로 위플래시는 토니 스타크의 라이벌 ‘저스틴 해머’와 손을 잡고 아이언맨을 공격하기 시작하고 이에 토니 스타크는 오랜 동료 제임스 로드를 위한 새로운 하이테크 수트를 제작 ‘워 머신’으로 거듭난 그와 함께 강력해진 적들과의 본격적 대결에 나서는데…!",
    starPoint: "7.37",
    audienceCount: "442만명",
    summary: "SF | 미국 | 125분",
  },
  {
    search: "토르 : 천둥의 신",
    synopsys:
      "신의 세계 ‘아스가르드’의 후계자로 강력한 파워를 지닌 천둥의 신 ‘토르’. 평소 거침없는…대가 등장하는데… 두 개의 세계 한 명의 영웅 모두의 운명을 건 최후의 격돌이 시작된다!",
    starPoint: "7.32",
    audienceCount: "169만명",
    summary: "판타지 | 미국 | 112분",
  },
  {
    search: "캡틴 아메리카1",
    synopsys:
      "포기를 모르는 자의 새로운 이름 ‘퍼스트 어벤져’ 세계 전쟁으로 암흑에 빠진 시기 한 남자가 군 입대를 자원한다. 그의 이름은 ‘스티브 로저스’. 남들보다 왜소하고 마른 체격으로 인해 입대마저 번번히 거부당하던 그는 포기를 모르는 근성과 강한 희생 정신을 인정받아 최고의 전사를 양성하는 ‘슈퍼 솔져’ 프로젝트에 스카우트된다. 비밀리에 진행된 실험을 통해 가장 완벽한 육체와 인간의 한계를 초월한 신체 능력을 얻게 된 스티브. 그는 모두에게 ‘캡틴’으로 불리며 시대의 영웅으로 새롭게 태어난다. 하지만 그의 등장에 맞서 거대한 ‘히드라’ 조직을 앞세운 적의 공격은 한층 막강해지고 그 핵심에 선 ‘레드 스컬’은 인류를 위협하는 최후의 전투를 준비하는데... 세계를 위협하는 전쟁 그 한가운데로 향한 ‘캡틴’ 슈퍼히어로의 역사로 남을 그의 활약이 시작된다!",
    starPoint: "7.8",
    audienceCount: "51만명",
    summary: "액션 | 미국 | 123분",
  },
  {
    search: "어벤져스1",
    synopsys:
      "지구의 안보가 위협당하는 위기의 상황에서 슈퍼히어로들을 불러모아 세상을 구하는, 일명 [어벤져스] 작전. 에너지원 ‘큐브’를 이용한 적의 등장으로 인류가 위험에 처하자 국제평화유지기구인 쉴드 (S.H.I.E.L.D)의 국장 닉 퓨리(사무엘 L.잭슨)는 [어벤져스] 작전을 위해 전 세계에 흩어져 있던 슈퍼히어로들을 찾아나선다. 아이언맨(로버트 다우니 주니어)부터 토르(크리스 헴스워스), 헐크(마크 러팔로), 캡틴 아메리카(크리스 에반스)는 물론, 쉴드의 요원인 블랙 위도우(스칼렛 요한슨), 호크 아이(제레미 레너)까지, 최고의 슈퍼히어로들이 [어벤져스]의 멤버로 모이게 되지만, 각기 개성이 강한 이들의 만남은 예상치 못한 방향으로 흘러가는데… 지구의 운명을 건 거대한 전쟁 앞에 [어벤져스] 작전은 성공할 수 있을까?",
    starPoint: "8.80",
    audienceCount: "708만명",
    summary: "액션 | 미국 | 142분",
  },
  {
    search: "아이언맨3",
    synopsys:
      "<어벤져스> 뉴욕 사건의 트라우마로 인해 영웅으로서의 삶에 회의를 느끼는 토니 스타크(로버트 다우니 주니어). 그가 혼란을 겪는 사이 최악의 테러리스트 만다린(벤 킹슬리)을 내세운 익스트리미스 집단 AIM이 스타크 저택에 공격을 퍼붓는다. 이 공격으로 그에게 남은 건 망가진 수트 한벌 뿐. 모든 것을 잃어버린 그는 다시 테러의 위험으로부터 세계와 사랑하는 여인(기네스 팰트로)를 지켜내야 하는 동시에 머릿속을 떠나지 않던 한가지 물음의 해답도 찾아야만 한다. 과연 그가 아이언맨인가? 수트가 아이언맨인가?",
    starPoint: "8.86",
    audienceCount: "900만명",
    summary: "SF | 미국, 중국 | 129분",
  },
  {
    search: "토르 : 다크월드",
    synopsys:
      "<어벤져스>의 뉴욕 사건 후 다시 신들의 고향인 아스가르드 왕국으로 돌아간 토르(크리스 헴스워스)와 로키(톰 히들스턴). 지구를 위협한 로키는 지하 감옥에 갇히고 토르는 아버지 오딘(안소니 홉킨스)과 함께 우주의 질서를 재정립하기 위해 나선다. 1년 후 지구에 혼자 남은 제인(나탈리 포트만)은 우연히 태초부터 존재해왔던 어둠의 종족 ‘다크 엘프’의 무기 ‘에테르’를 얻게 된다. 이 사실을 안 ‘다크 엘프’의 리더 ‘말레키스’는 ‘에테르’를 되찾기 위해 제인과 아스가르드를 공격하고 토르는 사랑하는 여인 제인과 아스가르드 왕국을 지키기 위해 로키에게 위험한 동맹을 제안하게 된다.",
    starPoint: "8.35",
    audienceCount: "304만명",
    summary: "액션 | 미국 | 112분",
  },
  {
    search: "캡틴 아메리카2",
    synopsys:
      "어벤져스의 뉴욕 사건 이후 닉 퓨리 블랙 위도우와 함께 쉴드의 멤버로 현대 생활에 적응해 살아가는 캡틴 아메리카. 어느 날 죽은 줄 알았던 친구 버키가 적 윈터 솔져가 되어 돌아오고 어벤져스를 향한 최악의 위기가 시작된다.",
    starPoint: "8.83",
    audienceCount: "396만명",
    summary: "액션 | 미국 | 136분",
  },
  {
    search: "가디언즈 오브 갤럭시1",
    synopsys:
      "자칭 전설의 무법자 스타로드, 그러나 현실은 우주를 떠도는 그저그런 좀도둑에 불과한 피터 퀼(크리스 프랫). 뜻하지 않게 갤럭시의 절대악 타노스와 로난의 타겟이 된 그는 감옥에서 만난 암살자 가모라(조 샐다나), 거구의 파이터 드랙스(데이브 바티스타), 현상금 사냥꾼 로켓(브래들리 쿠퍼)과 그루트(빈 디젤) 콤비와 불편한 동맹을 맺고 일명 ‘가디언즈 오브 갤럭시’를 결성한다. 범상치 않은 화려한 과거를 지닌 이들이 과연 120억 명의 운명을 구할 유일한 희망이 될 수 있을까? 흩어지면 무법자, 뭉치면 히어로 차원이 다른 마블의 새로운 세계를 목격하라!",
    starPoint: "8.64",
    audienceCount: "134만명",
    summary: "액션 | 미국 | 122분",
  },
  {
    search: "어벤져스 : 에이지 오브 울트론",
    synopsys:
      "쉴드의 숙적 히드라는 연구를 통해 새로운 능력자 막시모프 남매를 탄생시키고 히드라의 기지를 공격하는 도중 토니 스타크는 완다 막시모프의 초능력으로 인해 자신이 가장 두려워하는 미래를 보게 된다. 이에 '뉴욕전쟁' 때와 같은 사태가 벌어지지 않도록 스타크는 배너 박사와 함께 지구를 지킬 최강의 인공지능 울트론을 탄생시키게 되지만 울트론은 예상과 다르게 지배를 벗어나 폭주하기 시작하는데...",
    starPoint: "8.59",
    audienceCount: "1,050만명",
    summary: "액션 | 미국 | 141분",
  },
  {
    search: "앤트맨1",
    synopsys:
      "하나뿐인 딸에게 멋진 아빠이고 싶지만 현실은 생계형 도둑인 스캇 랭(폴 러드). 어느 날 그에게 몸을 자유자재로 늘리거나 줄일 수 있는 핌 입자를 개발한 과학자 행크 핌(마이클 더글라스)이 찾아와 수트와 헬멧을 건네며 ‘앤트맨’이 되어 줄 것을 요청한다. 어리둥절 하지만 일단 한번 해보기로 결심한 스캇 랭은 행크 핌의 딸인 호프(에반젤린 릴리)의 도움을 받아 점차 히어로의 면모를 갖추어가고 그의 스승이자 멘토인 행크 핌 박사를 도와 핌 입자를 악용하려는 세력을 막아야 하는데… 마블 유니버스의 새로운 세계가 이제 그의 손에 달렸다!",
    starPoint: "8.71",
    audienceCount: "284만명",
    summary: "액션 | 미국, 영국 | 117분",
  },
  {
    search: "캡틴 아메리카3",
    synopsys:
      "어벤져스 VS 어벤져스 분열은 시작되었다! 어벤져스와 관련된 사고로 부수적인 피해가 일어나자 정부는 어벤져스를 관리하고 감독하는 시스템인 일명 ‘슈퍼히어로 등록제’를 내놓는다. 어벤져스 내부는 정부의 입장을 지지하는 찬성파(팀 아이언맨)와 이전처럼 정부의 개입 없이 자유롭게 인류를 보호해야 한다는 반대파(팀 캡틴)로 나뉘어 대립하기 시작하는데...",
    starPoint: "8.82",
    audienceCount: "867만명",
    summary: "액션 | 미국 | 147분",
  },
  {
    search: "닥터 스트레인지",
    synopsys:
      "불의의 사고로 절망에 빠진 천재 외과의사 ‘닥터 스트레인지(베네딕트 컴버배치)’. 마지막 희망을 걸고 찾아 간 곳에서 ‘에인션트 원(틸다 스윈튼)’을 만나 세상을 구원할 강력한 능력을 얻게 되면서 모든 것을 초월한 최강의 히어로로 거듭나는데...",
    starPoint: "8.88",
    audienceCount: "544만명",
    summary: "액션 | 미국 | 115분",
  },
  {
    search: "가디언즈 오브 갤럭시 VOL.2",
    synopsys:
      "최강 빌런 ‘타노스’에 맞서 은하계를 구하고 최고의 해결사로 등극한 ‘가.오.갤’ 멤버들. 하지만 외계 여사제 ‘아이샤’가 맡긴 임무를 수행하던 중 실수로 또 다시 쫓기는 신세로 전락한다. 한편 자신에게 숨겨진 힘의 원천에 대해 고민하던 리더 ‘스타로드’는 갑작스레 나타난 아버지로 인해 또 다른 위기에 빠지게 되는데…",
    starPoint: "9.05",
    audienceCount: "273만명",
    summary: "액션 | 미국 | 136분",
  },
  {
    search: "스파이더맨 : 홈커밍",
    synopsys:
      "‘시빌 워’ 당시 ‘토니 스타크’(로버트 다우니 주니어)에게 발탁되어 대단한 활약을 펼쳤던 스파이더맨 ‘피터 파커’(톰 홀랜드). 그에게 새로운 수트를 선물한 ‘토니 스타크’는 위험한 일은 하지 말라며 조언한다. 하지만 허세와 정의감으로 똘똘 뭉친 ‘피터 파커’는 세상을 위협하는 강력한 적 ‘벌처’(마이클 키튼)에 맞서려 하는데… 아직은 어벤져스가 될 수 없는 스파이더맨 숙제보다 세상을 구하고 싶은 스파이더맨 그는 과연 진정한 히어로로 거듭날 수 있을 것인가!",
    starPoint: "8.83",
    audienceCount: "725만명",
    summary: "액션 | 미국 | 133분",
  },
  {
    search: "토르 : 라그나로크",
    synopsys:
      "죽음의 여신 ‘헬라’가 아스가르드를 침략하고 세상은 모든 것의 종말 ‘라그나로크’의 위기에 처한다. 헬라에게 자신의 망치마저 파괴당한 토르는 어벤져스 동료인 헐크와도 피할 수 없는 대결을벌이면서 절체절명의 위기에 빠지게 되는데…",
    starPoint: "9.03",
    audienceCount: "485만명",
    summary: "액션 | 미국 | 130분",
  },
  {
    search: "블랙 팬서1",
    synopsys:
      "‘시빌 워’ 이후 와칸다의 왕위를 계승한 티찰라(채드윅 보스만)는 와칸다에만 존재하는 최강 희귀 금속 ‘비브라늄’과 왕좌를 노리는 숙적들의 음모가 전세계적인 위협으로 번지자 세상을 구할 히어로 ‘블랙 팬서’로서 피할 수 없는 전쟁에 나서는데…",
    starPoint: "8.33",
    audienceCount: "539만명",
    summary: "액션 | 미국 | 135분",
  },
  {
    search: "어벤져스 : 인피니티 워",
    synopsys:
      "새로운 조합을 이룬 어벤져스 역대 최강 빌런 타노스에 맞서 세계의 운명이 걸린 인피니티 스톤을 향한 무한 대결이 펼쳐진다! 마블의 클라이맥스를 목격하라!",
    starPoint: "9.08",
    audienceCount: "1,123만명",
    summary: "액션 | 미국 | 149분",
  },
  {
    search: "앤트맨과 와스프",
    synopsys:
      "‘시빌 워’ 사건 이후 은둔하며 히어로와 가장의 역할 사이에서 고민 중이던 ‘앤트맨’과 새로운 파트너 ‘와스프’ 앞에 정체불명의 빌런 ‘고스트’가 등장한다. 시공간의 개념이 사라진 양자 영역으로 들어갈 수 있는 기술을 훔쳐 달아난 고스트를 쫓던 앤트맨과 와스프는 상상도 못했던 상황에 직면하는데…",
    starPoint: "8.85",
    audienceCount: "544만명",
    summary: "액션 | 미국 | 118분",
  },
  {
    search: "캡틴 마블",
    synopsys:
      "1995년 공군 파일럿 시절의 기억을 잃고 크리족 전사로 살아가던 캐럴 댄버스(브리 라슨)가 지구에 불시착한다. 쉴드 요원 닉 퓨리(사무엘 L. 잭슨)에게 발견되어 팀을 이룬 그들은 지구로 향하는 더 큰 위협을 감지하고 힘을 합쳐 전쟁을 끝내야 하는데…",
    starPoint: "8.45",
    audienceCount: "580만명",
    summary: "액션 | 미국 | 123분",
  },
  {
    search: "어벤져스 : 엔드게임",
    synopsys:
      "인피니티 워 이후 절반만 살아남은 지구 마지막 희망이 된 어벤져스 먼저 떠난 그들을 위해 모든 것을 걸었다! 위대한 어벤져스 운명을 바꿀 최후의 전쟁이 펼쳐진다!",
    starPoint: "9.49",
    audienceCount: "1,397만명",
    summary: "액션 | 미국 | 181분",
  },
  {
    search: "스파이더맨 : 파 프롬 홈",
    synopsys:
      "‘엔드게임’ 이후 변화된 세상 스파이더맨 ‘피터 파커’는 학교 친구들과 유럽 여행을 떠나게 된다. 그런 그의 앞에 ‘닉 퓨리’가 등장해 도움을 요청하고 정체불명의 조력자 ‘미스테리오’까지 합류하게 되면서 전 세계를 위협하는 새로운 빌런 ‘엘리멘탈 크리쳐스’와 맞서야만 하는 상황에 놓이게 되는데…",
    starPoint: "8.99",
    audienceCount: "802만명",
    summary: "액션 | 미국 | 129분",
  },
  {
    search: "블랙위도우",
    synopsys:
      "어벤져스의 히어로 블랙 위도우 ‘나타샤 로마노프’ (스칼렛 요한슨)는 자신의 과거와 연결된 레드룸의 거대한 음모와 실체를 깨닫게 된다. 상대의 능력을 복제하는 빌런 ‘태스크마스터’와 새로운 위도우들의 위협에 맞서 목숨을 건 반격을 시작하는 ‘나타샤’는 스파이로 활약했던 자신의 과거 뿐 아니라 어벤져스가 되기 전 함께했던 동료들을 마주해야만 하는데… 폭발하는 리얼 액션 카타르시스! MCU의 새로운 시대를 시작할 첫 액션 블록버스터를 만끽하라!",
    starPoint: "9.07",
    audienceCount: "295만명",
    summary: "액션 | 미국 | 134분",
  },
  {
    search: "샹치와 텐 링즈의 전설",
    synopsys:
      "초인적인 능력을 가진 ‘텐 링즈’의 힘으로 수세기 동안 어둠의 세상을 지배해 온 ‘웬우’ '샹치’는 아버지 ‘웬우’ 밑에서 암살자로 훈련을 받았지만 이를 거부하고 평범함 삶을 선택한다. 그러나 ‘샹치’는 목숨을 노리는 자들의 습격으로 더 이상 운명을 피할 수 없다는 것을 직감하고 어머니가 남긴 가족의 비밀과 내면의 신비한 힘을 일깨우게 된다 벗어나고 싶은 과거이자 그 누구보다 두려운 아버지 ‘웬우’를 마주해야 하는 ‘샹치’ 악이 될 것인가? 구원이 될 것인가? 마블의 새로운 시대 세상에 없던 힘이 탄생한다!",
    starPoint: "8.10",
    audienceCount: "1,816명",
    summary: "액션 | 미국, 오스트레일리아 | 132분",
  },
  {
    search: "베놈 2 : 렛 데어 비 카니지",
    synopsys:
      "미워할 수 없는 빌런 히어로 ‘베놈’(톰 하디) 앞에 사상 최악의 빌런 ‘카니지’(우디 해럴슨)가 나타나 대혼돈의 시대를 예고하면서 그와 피할 수 없는 대결을 그린 액션 블록버스터.",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "이터널스",
    synopsys:
      "마블 스튜디오의 <이터널스>는 수 천년에 걸쳐 그 모습을 드러내지 않고 살아온 불멸의 히어로들이 <어벤져스: 엔드게임> 이후 인류의 가장 오래된 적 '데비안츠'에 맞서기 위해 다시 힘을 합치면서 벌어지는 이야기",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "스파이더맨 : 노 웨이 홈",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "닥터 스트레인지 인 더 멀티버스 오브 매드니스",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "토르 : 러브 앤 썬더",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "블랙팬서 : 와칸다 포에버",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "더 마블스",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "앤트맨과 와스프 : 퀀터매니아",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "가디언즈 오브 갤럭시 VOL.3",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "마블 블레이드1",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
  {
    search: "마블 판타스틱4",
    synopsys: "Coming Soon!",
    starPoint: "-",
    audienceCount: "-",
    summary: "-",
  },
];

const movies = movies_launch.concat(movies_schedule);
